# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Java Simple App

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build-test-deploy:
    uses: poc-github-framework/java-workflow/.github/workflows/framework.yml@main
    permissions:
      checks: write
      pull-requests: write
    secrets:
      ARTIFACTORY_PASSWORD: ${{ secrets.MAVEN_ARTIFACTORY_PASSWORD }}
    with:
      JAVA_VERSION: ${{ vars.JAVA_VERSION }}
      ARTIFACTORY_USERNAME:  ${{ vars.MAVEN_ARTIFACTORY_USERNAME }}
      ARTIFACTORY_SETTINGS_XML_URL: ${{ vars.MAVEN_ARTIFACTORY_SETTINGS_XML_URL }}
      MAVEN_POM_FILE: ${{ vars.MAVEN_POM_FILE }}
      MAVEN_GOALS: ${{ vars.MAVEN_GOALS }}
      MAVEN_OPTS: ${{ vars.MAVEN_OPTS }}
      
