name: Test Activity Workflow
on: 
  workflow_dispatch:
jobs:
  greetings-job:
    runs-on: ubuntu-latest
    env:
      buildNumber: $(date '+%Y%m%d')
    steps:
      - name: Build Version
        id: version
        run: echo "::set-output name=buildVersion::$(date +'%Y-%m-%d'.$GITHUB_RUN_ID)"
      - name: welcome-step
        run: |
          echo "RUN NUMBER $GITHUB_RUN_NUMBER"
          echo "RUN ID $GITHUB_RUN_ID"
          echo "build Version ${{ steps.version.outputs.buildVersion }}"
