name: Test Activity Workflow
on: 
  workflow_dispatch:
jobs:
  greetings-job:
    runs-on: ubuntu-latest
    steps:
      - name: welcome-step
        run: |
          echo "RUN NUMBER ${{ GITHUB_RUN_NUMBER }}"
          echo "RUN ID ${{ GITHUB_RUN_ID }}"
